molgenis/NGS_Automated

copyProjectDataToPrm.sh
sharedConfig.cfg
sharedFunctions.bash

* Configurable logging with log4Bash.
* Improved error handling.
* Positional -> named arguments.

Work in progress for 2.x

---

bin/copyRawDataToPrm.sh
etc/boxy.cfg

first new version copyRawDataToPrm.sh

first new version copyRawDataToPrm.sh

---

bin/copyRawDataToPrm.sh
bin/startPipeline.sh
etc/sharedConfig.cfg

* consistent indentation.
* improved logging.
* removed unused commandline args.
* introduced variable for samplesheet extension.

Improvements for startPipeline

---

bin/copyProjectDataToPrm.sh
bin/copyRawDataToPrm.sh
bin/startPipeline.sh

Always specify format for printf and put newlines in format definition instead of in value(s) that will be formatted.

Improved syntax for printf statements

---

bin/copyProjectDataToPrm.sh
bin/copyRawDataToPrm.sh

* Fixes for compliance with code style conventions for this repo.
* Changed ${_log_File} to ${_logfile}.
* Removed unnecessary temp ${fileP} variable.
* Added commented code and ToDo comments in places where job control is temporarily switched from TMP to PRM to prevent that we forget to change it back once proper PRM mounts are available on GD clusters.

Cosmetics.

---

bin/cleanup.sh
bin/copyProjectDataToPrm.sh
bin/copyRawDataToPrm.sh
bin/notifications.sh
bin/startPipeline.sh

Fixes bug when executing scripts in non-login shell like for example when executed by cron.

Bugfix for "logname: no login name" error.

---

bin/copyRawDataToPrm.sh

- check for demultiplexing only.
- split rest of the project per csv for pipeline analysis.

Skip pipeline option

---

bin/copyProjectDataToPrm.sh
etc/sharedConfig.cfg

Push MultiQC statistics into ChronQC database after copying projectdata to prm.

Push MultiQC statistics into ChronQC database after copying projectdata to prm.

---

bin/processGsRawData.sh
etc/cron.d/boxy.umcg-gaf-ateambot.cron
etc/cron.d/boxy.umcg-gaf-dm.cron
etc/cron.d/boxy.umcg-gd-dm.cron
etc/cron.d/calculon.umcg-gaf-ateambot.cron
etc/cron.d/calculon.umcg-gaf-dm.cron
etc/cron.d/calculon.umcg-gd-dm.cron
etc/cron.d/leucine-zipper.umcg-gd-ateambot.cron
etc/cron.d/leucine-zipper.umcg-gd-dm.cron
etc/cron.d/zinc-finger.umcg-gd-ateambot.cron
etc/cron.d/zinc-finger.umcg-gd-dm.cron
etc/zf-ds.cfg

* Added comments and extra log line to processGsRawData.sh
* Added -bare suffix for NGS_Automated version number in cron templates.
* Added config file for zf-ds.gcc.rug.nl

Minor bug fixes for configs/templates.

---

bin/processGsRawData.sh
etc/cron.d/zinc-finger.umcg-gd-dm.cron
etc/cron.d/zinc-finger.umcg-genomescan-ateambot.cron
etc/umcg-genomescan.cfg

* Changed crontab templates for processing of GenomeScan data by ateambot user as opposed to dm user.
* Removed notifications for analysis step not performed in genomescan group.
* Added log output also to ${JOB_CONTROLE_FILE_BASE}.[started|finished|failed], so it will be picked up by notifications.sh as body for email messages.

Small improvements for processing GenomeScan data.

---

bin/copyProjectDataToPrm.sh

* copyProjectDataToPrm.sh:
* Bugfix: do not move the *.started file premataturely to *.failed as this will result in crash when the file cannot be moved later on.
* Fixed some indentation / formatting / code style.

Improved copyProjectDataToPrm.sh

---

bin/demultiplexingTiming.sh

with notification if *.demultiplexing.started is older than 1h

script to check how old the .demultiplexing.stared is

---

bin/copyProjectDataToPrm.sh
lib/sharedFunctions.bash

- removing samplesheet from tmp when copyProjectDataToPrm is done
- fix uploading to new version Molgenis (7.0)
- better error message when molgenis server is down

last fixes (see comment)

---

bin/copyRawDataToPrmTiming.sh
bin/pipelineTiming.sh

and made a check if there are no projects to check, then quit the scripts

changed user for copyRawDataToPrmTiming.sh 

---

bin/copyProjectDataToPrm.sh

so diagnostics can see from which project the per sample PennCNVs are

dir name change 

---

bin/calculateProjectMd5s.sh
bin/copyProjectDataToPrm.sh

* Code cleanup / code style fixes: white space, added missing quotes, the usual...
* Make sure that the simulated symlink that triggers data processing by Darwin is written last.

Code cleanup and re-ordered creation of simulated symlinks.

---

bin/processGsRawData.sh

* ```processGsRawData.sh```:
* Bugfix: changed typo "empy" -> "empty" in ```requiredSamplesheetColumns``` array.
* Feature: automagically fetch samplesheet from ```.../Samplesheet/archive/``` subfolder when present there and missing from ```.../Samplesheet/new/``` subfolder. This prevent failure to process a batch when one or more projects/pools in that batch were re-sequenced, because a previous sequence run failed QC (e.g. yield to low) and the lab forgot to put a new samplesheet in ```.../Samplesheet/new/```

processGsRawData.sh: fixed typo and look in archive folder for missing samplesheets.

---

bin/copyRawDataToPrmTiming.sh
bin/demultiplexingTiming.sh

Had er toch nog een paar over het hoofd gezien, maar Jenkins niet ;)

Last spaces -> tabs.

---

bin/copyRawDataToPrm.sh
bin/pullRawDataFromDS.sh

* Changed order a bit and updated comments to make differences between instances of Track & Trace more clear.
* Fixed typo in comment.

Minor update

---

bin/trendAnalyse.sh
etc/sharedConfig.cfg
etc/umcg-atd.cfg
etc/umcg-gd.cfg
templates/chronqc.AlignmentSummaryMetrics.json
templates/chronqc.ArrayInzetten.json
templates/chronqc.Capturing.json
templates/chronqc.Concentratie.json
templates/chronqc.HsMetrics.json
templates/chronqc.NGSInzetten.json
templates/chronqc.SamplePrep.json
templates/chronqc.SequenceRun.json
templates/chronqc.flagstat.json
templates/chronqc.general.json
templates/chronqc.insertSize.json

- templates added to repo
- extra reports
- merge of capturing data types
- bugfixed

trendanalysis update

---

bin/trendAnalyse.sh
etc/zf-ds.cfg

- updated shared configs
- small changes trendAnalysis.sh

final things

---

bin/trendAnalyse.sh
etc/umcg-gd.cfg
templates/chronqc.Concentratie.json
templates/reports.zf-ds.cfg

- data can be collected from both PRMs
- only the nimbus data is shown for the concentration graphs

minor changes

---

bin/copyProjectDataToPrm.sh
bin/notifications.sh

Improved handling of notifications in combination with forwarding messages to mail using power automate.

Improved handling of notifications.

---

bin/trendAnalyse.sh
etc/umcg-atd.cfg
templates/chronqc.seqOverview.json

Data generated with the new multiQC can also be added to the data base

updated trendanalysis

---

bin/PullAndProcessGsRawData.sh
bin/createInhouseSamplesheetFromGS.py
etc/sharedConfig.cfg

a new version of ngs-utils is needed. before NGS_Automated gets a new release, ngs-utils should get a new release en be put in the sharedConfig.cfg

make pullAndProcessGSRawData.sh also fit for RNA projects
